insert into departments (id, name) values (nextval('entity_seq'), 'Marketing');
insert into departments (id, name) values (nextval('entity_seq'), 'Sales');
insert into departments (id, name) values (nextval('entity_seq'), 'Accounting');
insert into departments (id, name) values (nextval('entity_seq'), 'Training');
insert into departments (id, name) values (nextval('entity_seq'), 'Engineering');

insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR48 3032 9753 51NI VUD4 6UKO P50');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'PT73 1367 0336 5600 7601 1192 1');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DE72 5293 0693 5810 0031 02');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'VG66 ZRUA 8057 9796 5259 7546');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'CH35 6933 5N0D IB8C AXGI C');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'LU82 820X ABKL KDRD SUWT');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'BH88 MTWU ALOE VH2A JNNK 7A');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'LT76 8960 7539 3088 5950');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'ME19 3116 9760 2650 1672 89');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DE27 1694 8855 2241 1123 41');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR45 4628 0264 96TL BV4A JV0Z J73');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'MU95 DSXI 6974 2778 9767 0482 522G RE');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'SE52 7572 6757 3190 3310 8946');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'SA41 24EV 7JOS L1CZ AVPG UIU1');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'HU19 4920 0670 7657 7632 3711 1775');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DK16 2858 4617 2640 82');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'MC89 4128 0054 79GX GJER APXJ J75');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'MD50 BFHA YIHE 7GFC 5RB5 8GVP');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'TN47 0792 9294 2174 5583 2412');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'MC21 1973 4640 84RJ YNRB JPRE W25');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'MC69 7722 8116 40BO J7WA 6JZQ T70');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DK68 2725 1092 3436 92');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'KZ34 333T URGA UUYT WKTB');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DK11 4534 7325 3647 21');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'AZ85 NLFQ AVF5 3IJG 2PCY ZWS2 I2ZJ');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DO35 SUUK 1905 1340 9031 3215 8603');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR21 4628 2052 38A0 AU08 ES95 V01');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR49 3376 5288 43LK 8T5S PPIY F43');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'BH05 HKRY UCXY UKNT F5SH R6');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR76 0433 8677 83NP L2PT FUZC N63');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'AE26 7905 3957 8770 7749 358');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'LV08 DEIV Y4XS WKTZ PLRC L');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FO10 8450 2194 7991 50');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'PT45 3324 0478 0483 8522 2847 2');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'PL96 6617 8686 8426 8235 2904 2799');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'LI10 5393 6OCG D2NL 4TYT 6');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR93 3186 9687 99TV 7WIS 0UC1 X85');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'LU68 190W GZBC AATF JM6M');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'RS86 7191 0436 4356 8878 12');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'LV72 ILKX OM8A 2WRJ NOKO 3');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'TR81 2754 4C3R A7HW RKRY 8LXL YV');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR71 6117 9890 46ZZ HSDS H1SF C76');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'DK26 4089 5306 9787 31');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'RS38 3802 7566 0413 5551 42');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'GL17 8923 9188 7739 28');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'MC69 7939 0035 43DM 5JGY BZLG 147');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'FR94 5818 1491 14HH H62M JQLV G13');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'BR60 5478 7854 5857 8449 6158 033O U');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'ES69 4508 2042 4276 7513 4818');
insert into employee_details (id, iban) values (nextval('entity_seq'), 'KW72 GQWW WMIZ 5696 H0GX FQLE LRK3 ZV');

insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Clemence', 'Brame', 72, 64060, 2, 6);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Tod', 'Gillaspy', 20, 91581, 5, 7);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Eleni', 'Dunne', 41, 60230, 1, 8);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Andrej', 'Castagna', 16, 35676, 1, 9);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Agatha', 'Brownsea', 53, 64498, 3, 10);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Ula', 'Draco', 44, 64852, 3, 11);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Koo', 'Georg', 67, 23027, 1, 12);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Essie', 'Pretsel', 53, 57889, 3, 13);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Jessy', 'Wallhead', 91, 70653, 3, 14);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Burl', 'Fevers', 37, 12082, 4, 15);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Simmonds', 'Saltwell', 73, 26155, 5, 16);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Eadmund', 'Shurville', 20, 76618, 1, 17);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hillery', 'Leheude', 67, 35388, 2, 18);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hanna', 'Manus', 69, 40456, 4, 19);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Cesya', 'Birdwhistell', 25, 84834, 5, 20);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Clementius', 'Marlow', 55, 53346, 1, 21);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hildagarde', 'Salerno', 31, 40912, 3, 22);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Brinna', 'Hawkswood', 37, 63830, 4, 23);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Ahmad', 'Cone', 65, 74725, 5, 24);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'El', 'Elfleet', 94, 27742, 1, 25);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Israel', 'Lemmertz', 33, 12867, 3, 26);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Keelby', 'Bailess', 20, 25620, 3, 27);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Karim', 'Barlow', 76, 48048, 2, 28);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Meta', 'Kingaby', 59, 20046, 5, 29);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Stavro', 'Cossans', 33, 77642, 4, 30);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Fancy', 'Elkins', 29, 85725, 4, 31);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Emelita', 'Hamlyn', 41, 85818, 4, 32);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Nikolaus', 'Fernando', 28, 62376, 3, 33);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Dulciana', 'MacNair', 71, 53409, 1, 34);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hadley', 'Kench', 48, 83195, 2, 35);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Brittani', 'Andresser', 36, 28483, 5, 36);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Stefano', 'Spaight', 95, 59352, 5, 37);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Althea', 'Lodwick', 45, 49922, 1, 38);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Rhetta', 'Sinnatt', 63, 85805, 4, 39);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hannah', 'McMurdo', 62, 67412, 1, 40);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hyacinth', 'Rabley', 56, 7623, 2, 41);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hermina', 'Akester', 43, 49316, 3, 42);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Rana', 'Keningley', 66, 47409, 2, 43);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Gale', 'Townson', 23, 57536, 1, 44);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Patrizio', 'Ayshford', 31, 13726, 1, 45);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Emmey', 'Vondrasek', 41, 86613, 2, 46);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Hakim', 'Kelberman', 81, 89020, 5, 47);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Irving', 'Catterill', 52, 52914, 4, 48);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Cindelyn', 'Duetschens', 57, 44958, 5, 49);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Herman', 'Griswood', 22, 8701, 2, 50);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Glynis', 'Skae', 86, 85547, 3, 51);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Adore', 'Edward', 91, 13954, 2, 52);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Salvidor', 'Pimer', 17, 15018, 3, 53);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Miranda', 'Molder', 66, 90808, 4, 54);
insert into employees (id, first_name, last_name, age, salary, dept_id, employee_details_id) values (nextval('entity_seq'), 'Curt', 'Amesbury', 80, 8545, 3, 55);

insert into projects (id, name) values (nextval('entity_seq'), 'Marketplace');
insert into projects (id, name) values (nextval('entity_seq'), 'Crypto engine');
insert into projects (id, name) values (nextval('entity_seq'), 'Sales CRM');
insert into projects (id, name) values (nextval('entity_seq'), 'Web portal');
insert into projects (id, name) values (nextval('entity_seq'), 'Search Engine');

insert into employees_projects (employee_id, project_id) values (56, 107);
insert into employees_projects (employee_id, project_id) values (57, 110);
insert into employees_projects (employee_id, project_id) values (58, 109);
insert into employees_projects (employee_id, project_id) values (59, 107);
insert into employees_projects (employee_id, project_id) values (60, 107);
insert into employees_projects (employee_id, project_id) values (61, 109);
insert into employees_projects (employee_id, project_id) values (62, 109);
insert into employees_projects (employee_id, project_id) values (63, 107);
insert into employees_projects (employee_id, project_id) values (64, 106);
insert into employees_projects (employee_id, project_id) values (65, 108);
insert into employees_projects (employee_id, project_id) values (66, 110);
insert into employees_projects (employee_id, project_id) values (67, 107);
insert into employees_projects (employee_id, project_id) values (68, 106);
insert into employees_projects (employee_id, project_id) values (69, 110);
insert into employees_projects (employee_id, project_id) values (70, 108);
insert into employees_projects (employee_id, project_id) values (71, 106);
insert into employees_projects (employee_id, project_id) values (72, 109);
insert into employees_projects (employee_id, project_id) values (73, 106);
insert into employees_projects (employee_id, project_id) values (74, 110);
insert into employees_projects (employee_id, project_id) values (75, 107);
insert into employees_projects (employee_id, project_id) values (76, 109);
insert into employees_projects (employee_id, project_id) values (77, 109);
insert into employees_projects (employee_id, project_id) values (78, 107);
insert into employees_projects (employee_id, project_id) values (79, 109);
insert into employees_projects (employee_id, project_id) values (80, 108);
insert into employees_projects (employee_id, project_id) values (81, 108);
insert into employees_projects (employee_id, project_id) values (82, 109);
insert into employees_projects (employee_id, project_id) values (83, 109);
insert into employees_projects (employee_id, project_id) values (84, 110);
insert into employees_projects (employee_id, project_id) values (85, 109);
insert into employees_projects (employee_id, project_id) values (86, 107);
insert into employees_projects (employee_id, project_id) values (87, 107);
insert into employees_projects (employee_id, project_id) values (88, 110);
insert into employees_projects (employee_id, project_id) values (89, 107);
insert into employees_projects (employee_id, project_id) values (90, 106);
insert into employees_projects (employee_id, project_id) values (91, 107);
insert into employees_projects (employee_id, project_id) values (92, 106);
insert into employees_projects (employee_id, project_id) values (93, 108);
insert into employees_projects (employee_id, project_id) values (94, 108);
insert into employees_projects (employee_id, project_id) values (95, 110);
insert into employees_projects (employee_id, project_id) values (96, 108);
insert into employees_projects (employee_id, project_id) values (97, 106);
insert into employees_projects (employee_id, project_id) values (98, 106);
insert into employees_projects (employee_id, project_id) values (99, 107);
insert into employees_projects (employee_id, project_id) values (100, 106);
insert into employees_projects (employee_id, project_id) values (101, 108);
insert into employees_projects (employee_id, project_id) values (102, 108);
insert into employees_projects (employee_id, project_id) values (103, 106);
insert into employees_projects (employee_id, project_id) values (104, 107);
insert into employees_projects (employee_id, project_id) values (105, 108);

insert into employees_projects (employee_id, project_id) values (56, 110);
insert into employees_projects (employee_id, project_id) values (57, 109);
insert into employees_projects (employee_id, project_id) values (58, 106);
insert into employees_projects (employee_id, project_id) values (59, 110);
insert into employees_projects (employee_id, project_id) values (60, 108);
insert into employees_projects (employee_id, project_id) values (61, 106);
insert into employees_projects (employee_id, project_id) values (62, 108);
insert into employees_projects (employee_id, project_id) values (63, 104);
insert into employees_projects (employee_id, project_id) values (64, 108);
insert into employees_projects (employee_id, project_id) values (65, 107);
insert into employees_projects (employee_id, project_id) values (66, 108);
insert into employees_projects (employee_id, project_id) values (67, 106);
insert into employees_projects (employee_id, project_id) values (68, 110);
insert into employees_projects (employee_id, project_id) values (69, 108);
insert into employees_projects (employee_id, project_id) values (70, 107);
insert into employees_projects (employee_id, project_id) values (71, 107);
insert into employees_projects (employee_id, project_id) values (72, 107);
insert into employees_projects (employee_id, project_id) values (73, 108);
insert into employees_projects (employee_id, project_id) values (74, 106);
insert into employees_projects (employee_id, project_id) values (75, 109);
insert into employees_projects (employee_id, project_id) values (76, 110);
insert into employees_projects (employee_id, project_id) values (77, 110);
insert into employees_projects (employee_id, project_id) values (78, 108);
insert into employees_projects (employee_id, project_id) values (79, 106);
insert into employees_projects (employee_id, project_id) values (80, 107);
insert into employees_projects (employee_id, project_id) values (81, 110);
insert into employees_projects (employee_id, project_id) values (82, 106);
insert into employees_projects (employee_id, project_id) values (83, 108);
insert into employees_projects (employee_id, project_id) values (84, 106);
insert into employees_projects (employee_id, project_id) values (85, 110);
insert into employees_projects (employee_id, project_id) values (86, 106);
insert into employees_projects (employee_id, project_id) values (87, 106);
insert into employees_projects (employee_id, project_id) values (88, 107);
insert into employees_projects (employee_id, project_id) values (89, 106);
insert into employees_projects (employee_id, project_id) values (90, 108);
insert into employees_projects (employee_id, project_id) values (91, 110);
insert into employees_projects (employee_id, project_id) values (92, 107);
insert into employees_projects (employee_id, project_id) values (93, 109);
insert into employees_projects (employee_id, project_id) values (94, 106);
insert into employees_projects (employee_id, project_id) values (95, 106);
insert into employees_projects (employee_id, project_id) values (96, 106);
insert into employees_projects (employee_id, project_id) values (97, 110);
insert into employees_projects (employee_id, project_id) values (98, 107);
insert into employees_projects (employee_id, project_id) values (99, 106);
insert into employees_projects (employee_id, project_id) values (100, 109);
insert into employees_projects (employee_id, project_id) values (101, 106);
insert into employees_projects (employee_id, project_id) values (102, 109);
insert into employees_projects (employee_id, project_id) values (103, 108);
insert into employees_projects (employee_id, project_id) values (104, 110);
insert into employees_projects (employee_id, project_id) values (105, 106);
